TARGET		= rlm_couchbase
SRCS		= rlm_couchbase.c callbacks.c util.c
HEADERS		= config.h util.h callbacks.h
RLM_CFLAGS	=
RLM_LIBS	= 

include ../rules.mak

$(STATIC_OBJS): $(HEADERS)

$(DYNAMIC_OBJS): $(HEADERS)
